name: image_cropper_platform_interface
description: A common platform interface for the image_cropper plugin.
repository: https://github.com/hnvn/flutter_image_cropper
version: 7.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface:
    git: 
      url: https://github.com/sonysm/flutter_image_cropper_gnk.git
      path: image_cropper_platform_interface
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
